d /var/lib/proaudio-player 0750 proaudio-player proaudio-player -
d /var/lib/proaudio-player-alert 0750 proaudio-player proaudio-player -
d /var/lib/proaudio-player-alert/media 0750 proaudio-player proaudio-player -
d /var/lib/proaudio-player-alert/mpd 0750 proaudio-player proaudio-player -
d /var/lib/proaudio-player-alert/mpd/playlists 0750 proaudio-player proaudio-player -
d /srv/music 0755 proaudio-player proaudio-player -
