pulse.cmd = [
    {
        cmd = "load-module"
        args = "module-null-sink sink_name=proaudio_player_music sink_properties=device.description=ProAudio_Player_Music_Bus rate=48000 channels=2"
        flags = [ ]
    }
    {
        cmd = "load-module"
        args = "module-null-sink sink_name=proaudio_player_alert sink_properties=device.description=ProAudio_Player_Alert_Bus rate=48000 channels=2"
        flags = [ ]
    }
]
