wireplumber.profiles = {
  main-embedded = {
    hardware.bluetooth = disabled
    hardware.video-capture = disabled

    monitor.bluez = disabled
    monitor.bluez-midi = disabled
    monitor.v4l2 = disabled
    monitor.libcamera = disabled
    monitor.alsa-midi = disabled

    support.dbus = disabled
    support.mpris = disabled
    api.notifications = disabled

    hooks.linking.pause-playback = disabled
  }
}

wireplumber.settings = {
  linking.pause-playback = false
}
